name: Deploy the site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          mkdir ~/.ssh
          printf '%s\n' "${{secrets.DEPLOY_KEY}}" > ~/.ssh/deploy_key
          printf "Host newsboat.org\n\tIdentityFile ~/.ssh/deploy_key\n\tUserKnownHostsFile=/dev/null\n\tStrictHostKeyChecking=no\n" > ~/.ssh/config
          chmod -R u=rwX,go= ~/.ssh
          ./deploy.sh
